### ISSUE TITLE
TeleOp TODO list

### ISSUE THREAD

**Issue by WillHescott** [Team74/FRC_2016_Python_Stronghold#17]
### TeleOp TODO List
- [x] Tank drive
- [x] Slow button
- [ ] Slow button variable speed
- [x] Pneumatic Control
- [ ] Debounce/ Control Dampening
- [ ] Feedback
- [ ] Appendage Control
  - [ ] Arm PID 
  - [x] Limit Switch Integration

**Comment by WubbaDuck** [comment]
@WillHescott Limit switch integration into the arm code as well as adding slow button variable speed can be two topics of work for this evening.
