### ISSUE TITLE
Autonomous TODO List

### ISSUE THREAD

**Issue by WillHescott** [Team74/FRC_2016_Python_Stronghold#18]
### Auton TODO List
- [ ] 3+ Auton options (Position, obstacle type, targeted goal)
- [ ] Encoder/Gyro Implementation
- [x] Basic Auton
- [ ] -Under Low Bar --> Score
